
import re

file_path = 'database/plsql/schema.sql'
with open(file_path, 'r') as f:
    content = f.read()

content = re.sub(r'id NUMBER\(20\) GENERATED BY DEFAULT(?: ON NULL)? AS IDENTITY PRIMARY KEY,', 'id NUMBER(20) PRIMARY KEY,', content)

tables = re.findall(r'CREATE TABLE (\w+) \(', content, flags=re.IGNORECASE)

sequences_and_triggers = '\n-- Sequences and Triggers for Auto-Increment --\n'
for table in tables:
    if table.lower() == 'sessions': continue
    
    seq_name = f'{table}_seq'
    trg_name = f'{table}_trg'
    
    sequences_and_triggers += f'''
CREATE SEQUENCE {seq_name} START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
/

CREATE OR REPLACE TRIGGER {trg_name}
BEFORE INSERT ON {table}
FOR EACH ROW
BEGIN
    IF :NEW.id IS NULL THEN
        :NEW.id := {seq_name}.NEXTVAL;
    END IF;
END;
/
'''

drop_script = '''
  PROCEDURE drop_seq_if_exists(p_seq_name VARCHAR2) IS
  BEGIN
    EXECUTE IMMEDIATE \\'DROP SEQUENCE \\' || p_seq_name;
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -2289 THEN -- ORA-02289: sequence does not exist
        RAISE;
      END IF;
  END;
'''

content = content.replace('END;', 'END;\n' + drop_script, 1)

for table in tables:
    if table.lower() == 'sessions': continue
    content = content.replace(f'drop_table_if_exists(\'{table.upper()}\');', f'drop_table_if_exists(\'{table.upper()}\');\n  drop_seq_if_exists(\'{table.upper()}_SEQ\');')

content += sequences_and_triggers

with open(file_path, 'w') as f:
    f.write(content)

